---
- hosts: all
  become: true
  
  tasks:

  - name: stop current running container
    command: docker container stop simple-devops-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm simple-devops-container
    ignore_errors: yes
   
  - name: remove docker image
    command: docker image rm amitksit/simple-docker-image    
    ignore_errors: yes
    
    #  - name: build docker image using war file
    #    command: docker build -t simple-devops-image .
    #    args:
    #      chdir: /opt/docker
  - name: pulldocker image from dockerhub
    command: docker pull amitksit/simple-devops-image:latest

  - name: create container using simple-devops-image
    command: docker container run -d --name simple-devops-container -p 8080:8080 amitksit/simple-devops-image
